<a href="https://colab.research.google.com/github/samitha278/miniVGG/blob/main/build_vgg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

## Simple Convolution function

In [4]:
def Convolution(image,kernel):

  x,y = image.shape

  a,b = kernel.shape

  feature_map = []

  for i in range(y-b):

    row = []

    for j in range(x-a):

      temp = (image[i:i+b,j:j+a] * kernel).sum(dim=(0,1))

      row.append(temp.item())

    feature_map.append(row)

  return torch.tensor(feature_map)

In [5]:
image = torch.randn((32,32))
kernel = torch.ones((3,3)) * (9**-1)


feature_map = Convolution(image,kernel)


In [6]:
feature_map.shape

torch.Size([29, 29])

## Convolution with stride

In [7]:
def Convolution(image,kernel,stride=(1,1)):

  x,y = image.shape
  a,b = kernel.shape

  r,c = stride

  feature_map = []

  for i in range(0,y-b,c):

    row = []

    for j in range(0,x-a,r):

      temp = (image[i:i+b,j:j+a] * kernel).sum(dim=(0,1))

      row.append(temp.item())

    feature_map.append(row)

  return torch.tensor(feature_map)

In [8]:
image = torch.randn((32,32))
kernel = torch.ones((3,3)) * (9**-1)


feature_map = Convolution(image,kernel,(2,1))      # 2: aloge side rows , 1: along side columns


In [9]:
feature_map.shape

torch.Size([29, 15])

## Adding Padding

In [10]:
def add_padding(image, padding):



  r,c = padding

  if r>0 :
    rows = torch.zeros((r,image.shape[1]))

    image = torch.cat((rows , image , rows),dim=0)

  if c>0:

    columns = torch.zeros((c,image.shape[0]))

    image = torch.cat((columns , image.T , columns),dim=0)


  return image.T



In [11]:
add_padding(torch.randn(2,2),(2,3))

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.2001,  1.4345,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.1159,  0.1599,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [12]:
def Convolution(image,kernel,stride=(1,1),padding = (0,0)):


  a,b = kernel.shape

  r,c = stride

  image_pd = image if padding==(0,0) else add_padding(image,padding)

  feature_map = []

  x,y = image_pd.shape

  for i in range(0,y-b,c):

    row = []

    for j in range(0,x-a,r):

      temp = (image_pd[i:i+b,j:j+a] * kernel).sum(dim=(0,1))

      row.append(temp.item())

    feature_map.append(row)

  return torch.tensor(feature_map)

In [13]:
image = torch.randn((32,32))
kernel = torch.ones((3,3)) * (9**-1)


feature_map = Convolution(image,kernel, padding=(2,2))


In [14]:
feature_map.shape

torch.Size([33, 33])

### Simple adding pad func

In [15]:
def add_padding2(matrix,padding):

  n,m = matrix.shape

  r,c = padding

  padded_matrix = torch.zeros((n+r*2,m+c*2))

  padded_matrix[r:r+n,c:c+m] = matrix

  return padded_matrix

In [16]:
add_padding2(torch.randn(2,2),(2,3))

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.1276, -0.6512,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.0422, -0.8412,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

### Adding Dialation

In [23]:
def Convolution(image,kernel,stride=(1,1),padding = (0,0),dilation=(1,1)):


  a,b = kernel.shape

  r,c = stride

  d1,d2 = dilation

  image_pd = image if padding==(0,0) else add_padding(image,padding)

  feature_map = []

  x,y = image_pd.shape

  for i in range(0,(y-b)//d2,c):

    row = []

    for j in range(0,(x-a)//d1,r):

      print(image_pd[i:i+b:d2,j:j+a:d1])
      temp = (image_pd[i:i+b:d2,j:j+a:d1] * kernel).sum(dim=(0,1))

      row.append(temp.item())

    feature_map.append(row)

  return torch.tensor(feature_map)

In [24]:
image = torch.randn((32,32))
kernel = torch.ones((3,3)) * (9**-1)


feature_map = Convolution(image,kernel, dilation=(2,2))

tensor([[ 0.4425,  0.5298],
        [-0.2325, -1.1987]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1